on: [push]

name: Azure ARM
env:
  bicepfilePath: ./aksdeployment.bicep
  resourceGroupLocation: eastus
  resourceGroupName: entproj-us
jobs:
  build:
    runs-on: ubuntu-latest
  
        
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access its
    - uses: actions/checkout@v3
    
      
    # Builds the Bicep template
    - name: bicep-build-output
      uses: Azure/bicep-build-action@v1.0.1
      with:
          bicepFilePath: ${{  env.bicepfilePath }}
          outputFilePath: ./main.json

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        path: ./main.json
  
  deploy: 
   runs-on: ubuntu-latest
   needs: [build]

   steps:
    - uses: actions/checkout@v3
    

    - name: Azure Login
      uses: Azure/login@v1
      with:
           creds: ${{ secrets.AZURE_CREDENTIALS }}
           
    - name: Az CLI Create Resource Group
      uses: Azure/CLI@v1
      with:
        inlineScript: |
          az group create \
          --name ${{ env.resourceGroupName }} \
          --location ${{ env.resourceGroupLocation }}
    - name: Deploy bicep to Azure
      uses: Azure/cli@v1
      with:
        inlineScript: |
          az deployment sub create \
          --template-file ${{  env.bicepfilePath }} \
          --resource-group ${{ env.resourceGroupName }} \
          --location ${{  env.resourceGroupLocation }}
    
