on: [push]
name: Azure ARM
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: c3d8fe47-5458-4f04-ab24-8dc3367ebf01 #${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: EntProj-rg
        template: ./aksdeployment.bicep
        parameters: 'location=eastus resourcePrefix=EntProj'
        failOnStdErr: false
